# Generated by Django 3.2.7 on 2021-11-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jypprj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='num',
            field=models.CharField(blank=True, max_length=250, verbose_name='글번호'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='num',
            field=models.CharField(blank=True, max_length=250, verbose_name='글번호'),
        ),
        migrations.AlterField(
            model_name='post',
            name='num',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='글번호'),
        ),
    ]
